[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true
ffi = false
fs_permissions = [{ access = "read", path = "./" }]

[profile.ci]
optimizer = true
optimizer_runs = 200
fuzz = { runs = 256 }
verbosity = 2

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}" }
